{% set name = "goawk" %}
{% set version = "1.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/benhoyt/goawk/archive/v{{ version }}.tar.gz
  sha256: f39d5b3ff50f3c16cbfaaa40eb01ec045092afa66988e9728661c65c0e5d6a93

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - goawk --help

about:
  home: https://benhoyt.com/writings/goawk
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: POSIX-compliant AWK interpreter written in Go
  dev_url: https://github.com/benhoyt/goawk

extra:
  recipe-maintainers:
    - danielnachun
