schema_version: 1

context:
  version: "1.32.0"

package:
  name: goawk
  version: ${{ version }}

source:
  url: https://github.com/benhoyt/goawk/archive/v${{ version }}.tar.gz
  sha256: 5425248c199bf506987af0deff9109bbdeecfb723f11b30c712c54a10b78f1a9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - goawk --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: POSIX-compliant AWK interpreter written in Go
  homepage: https://benhoyt.com/writings/goawk
  repository: https://github.com/benhoyt/goawk

extra:
  recipe-maintainers:
    - danielnachun
