schema_version: 1

context:
  version: 1.30.1

package:
  name: goawk
  version: ${{ version }}

source:
  url: https://github.com/benhoyt/goawk/archive/v${{ version }}.tar.gz
  sha256: 7f2964b474ac3d2d41b5a9bf5a18cd3ee369b2c1cd7aa405299b385ff20ea5db

build:
  number: 1

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - goawk --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: POSIX-compliant AWK interpreter written in Go
  homepage: https://benhoyt.com/writings/goawk
  repository: https://github.com/benhoyt/goawk

extra:
  recipe-maintainers:
    - danielnachun
